// Code generated by goctl. DO NOT EDIT.
package types

type ActionRequest struct {
	VideoID    int    `form:"video_id" json:"video_id"`
	ActionType int8   `form:"action_type,options=1|2" json:"action_type" ` // 1-点赞，2-取消点赞
	ActorID    uint32 `json:"actor_id" form:"actor_id,optional"`           // 操作者id
}

type ActionResponse struct {
	StatusCode uint32 `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg"`  // 返回状态描述
}

type ListRequest struct {
	UserID  uint32 `form:"user_id" json:"user_id"`
	ActorID uint32 `json:"actor_id" form:"actor_id,optional"`
}

type ListResponse struct {
	StatusCode uint32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string  `json:"status_msg"`  // 返回状态描述
	VideoList  []Video `json:"video_list"`
}

type User struct {
	ID              uint32 `json:"id"`               // 用户id
	Name            string `json:"name"`             // 用户名称
	FollowCount     uint32 `json:"follow_count"`     // 关注总数
	FollowerCount   uint32 `json:"follower_count"`   // 粉丝总数
	IsFollow        bool   `json:"is_follow"`        // true-已关注，false-未关注
	Avatar          string `json:"avatar"`           // 用户头像
	BackgroundImage string `json:"background_image"` // 用户个人页顶部大图
	Signature       string `json:"signature"`        // 个人简介
	TotalFavorited  uint32 `json:"total_favorited"`  // 获赞数量
	WorkCount       uint32 `json:"work_count"`       // 作品数量
	FavoriteCount   uint32 `json:"favorite_count"`   // 点赞数量
}

type Video struct {
	Id            uint32 `json:"id"`
	Author        *User  `json:"author"`
	PlayUrl       string `json:"play_url"`
	CoverUrl      string `json:"cover_url"`
	FavoriteCount uint32 `json:"favorite_count"`
	CommentCount  uint32 `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}
