// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"min-tiktok/services/user/internal/logic"
	"min-tiktok/services/user/internal/svc"
	"min-tiktok/services/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUserInfo(ctx context.Context, in *user.UserRequest) (*user.UserResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServer) CheckUserExist(ctx context.Context, in *user.UserExistRequest) (*user.UserExistResponse, error) {
	l := logic.NewCheckUserExistLogic(ctx, s.svcCtx)
	return l.CheckUserExist(in)
}
