// Code generated by goctl. DO NOT EDIT.
// Source: feedback.proto

package server

import (
	"context"

	"min-tiktok/services/feedback/feedback"
	"min-tiktok/services/feedback/internal/logic"
	"min-tiktok/services/feedback/internal/svc"
)

type FeedbackServer struct {
	svcCtx *svc.ServiceContext
	feedback.UnimplementedFeedbackServer
}

func NewFeedbackServer(svcCtx *svc.ServiceContext) *FeedbackServer {
	return &FeedbackServer{
		svcCtx: svcCtx,
	}
}

func (s *FeedbackServer) Feedback(ctx context.Context, in *feedback.FeedbackRequest) (*feedback.FeedbackResponse, error) {
	l := logic.NewFeedbackLogic(ctx, s.svcCtx)
	return l.Feedback(in)
}

func (s *FeedbackServer) ListRecommendWithFeedback(ctx context.Context, in *feedback.ListRecommendRequest) (*feedback.ListRecommendResponse, error) {
	l := logic.NewListRecommendWithFeedbackLogic(ctx, s.svcCtx)
	return l.ListRecommendWithFeedback(in)
}
