// Code generated by goctl. DO NOT EDIT.
// Source: auths.proto

package server

import (
	"context"

	"min-tiktok/services/auths/auths"
	"min-tiktok/services/auths/internal/logic"
	"min-tiktok/services/auths/internal/svc"
)

type AuthsServer struct {
	svcCtx *svc.ServiceContext
	auths.UnimplementedAuthsServer
}

func NewAuthsServer(svcCtx *svc.ServiceContext) *AuthsServer {
	return &AuthsServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthsServer) Register(ctx context.Context, in *auths.RegisterRequest) (*auths.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AuthsServer) Login(ctx context.Context, in *auths.LoginRequest) (*auths.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthsServer) Authentication(ctx context.Context, in *auths.AuthsRequest) (*auths.AuthsResponse, error) {
	l := logic.NewAuthenticationLogic(ctx, s.svcCtx)
	return l.Authentication(in)
}
