services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    ports:
      - "9200:9200"
      - "9300:9300"
    mem_limit: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - Tiktok
  kibana:
    image: docker.io/library/kibana:7.3.2
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - Tiktok
networks:
  Tiktok: