// Code generated by goctl. DO NOT EDIT.
package types

type Message struct {
	ID         uint32 `json:"id"`
	ToUserID   uint32 `json:"to_user_id"`
	FromUserID uint32 `json:"from_user_id"`
	Content    string `json:"content"`
	CreateTime uint64 `json:"create_time"`
}

type MessageActionReq struct {
	ActorId    uint32 `form:"actor_id"`
	ToUserID   uint32 `form:"to_user_id"`
	ActionType uint32 `form:"action_type"` // 1- 发送消息
	Content    string `form:"content"`
}

type MessageActionResp struct {
	StatusCode uint32 `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type MessageChatReq struct {
	ActorId    uint32 `form:"actor_id"`
	ToUserID   uint32 `form:"to_user_id"`
	PreMsgTime uint64 `form:"pre_msg_time,optional"`
}

type MessageChatResp struct {
	StatusCode  uint32     `json:"status_code"`
	StatusMsg   string     `json:"status_msg"`
	MessageList []*Message `json:"message_list"`
}
