// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"min-tiktok/services/message/internal/logic"
	"min-tiktok/services/message/internal/svc"
	"min-tiktok/services/message/message"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) MessageList(ctx context.Context, in *message.MessageListRequest) (*message.MessageListResponse, error) {
	l := logic.NewMessageListLogic(ctx, s.svcCtx)
	return l.MessageList(in)
}

func (s *MessageServer) MessageAction(ctx context.Context, in *message.MessageActionRequest) (*message.MessageActionResponse, error) {
	l := logic.NewMessageActionLogic(ctx, s.svcCtx)
	return l.MessageAction(in)
}
