// Code generated by goctl. DO NOT EDIT.
// Source: publish.proto

package server

import (
	"context"

	"min-tiktok/services/publish/internal/logic"
	"min-tiktok/services/publish/internal/svc"
	"min-tiktok/services/publish/publish"
)

type PublishServer struct {
	svcCtx *svc.ServiceContext
	publish.UnimplementedPublishServer
}

func NewPublishServer(svcCtx *svc.ServiceContext) *PublishServer {
	return &PublishServer{
		svcCtx: svcCtx,
	}
}

func (s *PublishServer) ActionVideo(ctx context.Context, in *publish.ActionVideoReq) (*publish.ActionVideoResp, error) {
	l := logic.NewActionVideoLogic(ctx, s.svcCtx)
	return l.ActionVideo(in)
}

func (s *PublishServer) ListVideo(ctx context.Context, in *publish.ListVideoReq) (*publish.ListVideoResp, error) {
	l := logic.NewListVideoLogic(ctx, s.svcCtx)
	return l.ListVideo(in)
}
