// Code generated by goctl. DO NOT EDIT.
package types

type RealtionActionResponse struct {
	StatusCode uint32 `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg"`  // 返回状态描述
}

type RealtionActionReuqest struct {
	UserID     uint32 `form:"to_user_id" json:"to_user_id"`
	ActorID    uint32 `json:"actor_id" form:"actor_id"`
	ActionType uint32 `json:"action_type" form:"action_type"`
}

type RelationFollowListRequest struct {
	UserID  uint32 `form:"user_id" json:"user_id"`
	ActorID uint32 `json:"actor_id" form:"actor_id"`
}

type RelationFollowListResponse struct {
	StatusCode uint32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string  `json:"status_msg"`  // 返回状态描述
	UserList   []*User `json:"user_list"`
}

type RelationFollowerListRequest struct {
	UserID  uint32 `form:"user_id" json:"user_id"`
	ActorID uint32 `json:"actor_id" form:"actor_id"`
}

type RelationFollowerListResponse struct {
	StatusCode uint32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string  `json:"status_msg"`  // 返回状态描述
	UserList   []*User `json:"user_list"`
}

type RelationFriendListRequest struct {
	UserID  uint32 `form:"user_id" json:"user_id"`
	ActorID uint32 `json:"actor_id" form:"actor_id"`
}

type RelationFriendListResponse struct {
	StatusCode uint32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string  `json:"status_msg"`  // 返回状态描述
	UserList   []*User `json:"user_list"`
}

type User struct {
	ID              uint32 `json:"id"`               // 用户id
	Name            string `json:"name"`             // 用户名称
	FollowCount     uint32 `json:"follow_count"`     // 关注总数
	FollowerCount   uint32 `json:"follower_count"`   // 粉丝总数
	IsFollow        bool   `json:"is_follow"`        // true-已关注，false-未关注
	Avatar          string `json:"avatar"`           // 用户头像
	BackgroundImage string `json:"background_image"` // 用户个人页顶部大图
	Signature       string `json:"signature"`        // 个人简介
	TotalFavorited  uint32 `json:"total_favorited"`  // 获赞数量
	WorkCount       uint32 `json:"work_count"`       // 作品数量
	FavoriteCount   uint32 `json:"favorite_count"`   // 点赞数量
}
