// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package favoriteclient

import (
	"context"

	"min-tiktok/services/favorite/favorite"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FavoriteListRequest  = favorite.FavoriteListRequest
	FavoriteListResponse = favorite.FavoriteListResponse
	FavoriteRequest      = favorite.FavoriteRequest
	FavoriteResponse     = favorite.FavoriteResponse
	UserInfo             = favorite.UserInfo
	Video                = favorite.Video

	Favorite interface {
		FavoriteAction(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error)
		FavoriteList(ctx context.Context, in *FavoriteListRequest, opts ...grpc.CallOption) (*FavoriteListResponse, error)
	}

	defaultFavorite struct {
		cli zrpc.Client
	}
)

func NewFavorite(cli zrpc.Client) Favorite {
	return &defaultFavorite{
		cli: cli,
	}
}

func (m *defaultFavorite) FavoriteAction(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error) {
	client := favorite.NewFavoriteClient(m.cli.Conn())
	return client.FavoriteAction(ctx, in, opts...)
}

func (m *defaultFavorite) FavoriteList(ctx context.Context, in *FavoriteListRequest, opts ...grpc.CallOption) (*FavoriteListResponse, error) {
	client := favorite.NewFavoriteClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}
