// Code generated by goctl. DO NOT EDIT.
package types

type Comment struct {
	ID         uint32 `json:"id" `
	User       User   `json:"user" `
	Content    string `json:"content" `
	CreateDate string `json:"create_date"` // mm-dd
}

type CommentActionRequest struct {
	VideoID     uint32 `json:"video_id" form:"video_id"` // 视频id
	ActorID     uint32 `json:"actor_id" form:"actor_id"`
	ActionType  uint32 `json:"action_type" form:"action_type"`        // 1-发布评论，2-删除评论
	CommentID   uint32 `json:"comment_id" form:"comment_id,optional"` // 要删除的评论id，在action_type=2的时候使用
	CommentText string `json:"comment_text" form:"comment_text,optional"`
}

type CommentActionResponse struct {
	Comment    Comment `json:"comment"`
	StatusCode uint32  `json:"status_code"`
	StatusMsg  string  `json:"status_msg"`
}

type CommentListRequest struct {
	VideoID uint32 `json:"video_id" form:"video_id"` // 用户id
	ActorID uint32 `json:"actor_id" form:"actor_id,optional"`
}

type CommentListResponse struct {
	ActorID     uint32    `json:"actor_id" form:"actor_id,optional"`
	CommentList []*Comment `json:"comment_list"`
	StatusCode  uint32    `json:"status_code"`
	StatusMsg   string    `json:"status_msg"`
}

type User struct {
	ID              uint32 `json:"id"`               // 用户id
	Name            string `json:"name"`             // 用户名称
	FollowCount     uint32 `json:"follow_count"`     // 关注总数
	FollowerCount   uint32 `json:"follower_count"`   // 粉丝总数
	IsFollow        bool   `json:"is_follow"`        // true-已关注，false-未关注
	Avatar          string `json:"avatar"`           // 用户头像
	BackgroundImage string `json:"background_image"` // 用户个人页顶部大图
	Signature       string `json:"signature"`        // 个人简介
	TotalFavorited  uint32 `json:"total_favorited"`  // 获赞数量
	WorkCount       uint32 `json:"work_count"`       // 作品数量
	FavoriteCount   uint32 `json:"favorite_count"`   // 点赞数量
}
