// Code generated by goctl. DO NOT EDIT.
package types

type ListVideosReq struct {
	LatestTime string `form:"latest_time,optional"`
	ActorId    uint32 `form:"actor_id,optional"`
}

type ListVideosResp struct {
	StatusCode uint32   `json:"status_code"`
	StatusMsg  string   `json:"status_msg"`
	NextTime   uint64   `json:"next_time"`
	VideoList  []*Video `json:"video_list"`
}

type User struct {
	ID              uint32 `json:"id"`               // 用户id
	Name            string `json:"name"`             // 用户名称
	FollowCount     uint32 `json:"follow_count"`     // 关注总数
	FollowerCount   uint32 `json:"follower_count"`   // 粉丝总数
	IsFollow        bool   `json:"is_follow"`        // true-已关注，false-未关注
	Avatar          string `json:"avatar"`           // 用户头像
	BackgroundImage string `json:"background_image"` // 用户个人页顶部大图
	Signature       string `json:"signature"`        // 个人简介
	TotalFavorited  uint32 `json:"total_favorited"`  // 获赞数量
	WorkCount       uint32 `json:"work_count"`       // 作品数量
	FavoriteCount   uint32 `json:"favorite_count"`   // 点赞数量
}

type Video struct {
	Id            uint32 `json:"id"`
	Author        *User  `json:"author"`
	PlayUrl       string `json:"play_url"`
	CoverUrl      string `json:"cover_url"`
	FavoriteCount uint32 `json:"favorite_count"`
	CommentCount  uint32 `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}
