---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-service
  namespace: tiktok
  labels:
    app: feedback-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-service
  template:
    metadata:
      name: feedback-service
      labels:
        app: feedback-service
    spec:
      imagePullSecrets:
        - name: harborsecret
      containers:
        - name: feedback-service
          image: swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:1.0
          imagePullPolicy: IfNotPresent

          command:
            - ./services/FeedbackService
          ports:
            - name: service-10007
              containerPort: 10007
              protocol: TCP
          volumeMounts:
            - name: project-etc-volume
              mountPath: /project/etc
            - name: project-logs-volume
              mountPath: /project/logs
      volumes:
        - name: project-etc-volume
          hostPath:
            path: /data/etc
#            不存在就创建
            type: DirectoryOrCreate
        - name: project-logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
      restartPolicy: Always

