---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  namespace: tiktok
  labels:
    app: feed-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      name: feed-service
      labels:
        app: feed-service
        version: "BUILD_HASH"
    spec:
      containers:
        - name: feed-service
          image: swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:latest
          imagePullPolicy: IfNotPresent
          command:
            - ./services/FeedService
          ports:
            - name: service-10002
              containerPort: 10002
              protocol: TCP
          volumeMounts:
            - name: project-etc-volume
              mountPath: /project/etc
            - name: project-logs-volume
              mountPath: /project/logs
      imagePullSecrets:
        - name: harborsecret
      volumes:
        - name: project-etc-volume
          hostPath:
            path: /data/etc
            type: DirectoryOrCreate
        - name: project-logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api
  namespace: tiktok
  labels:
    app: feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-api
  template:
    metadata:
      name: feed-api
      labels:
        app: feed-api
        version: "BUILD_HASH"
    spec:
      containers:
        - name: feed-api
          image: swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:latest
          imagePullPolicy: IfNotPresent
          command:
            - ./apis/FeedApi
          ports:
            - containerPort: 8890
              protocol: TCP
          volumeMounts:
            - name: project-etc-volume
              mountPath: /project/etc
            - name: project-logs-volume
              mountPath: /project/logs
      imagePullSecrets:
        - name: harborsecret
      volumes:
        - name: project-etc-volume
          hostPath:
            path: /data/etc
            type: DirectoryOrCreate
        - name: project-logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: feed-api
  namespace: tiktok
spec:
  selector:
    app: feed-api
  ports:
    -
      port: 8890
      targetPort: 8890