---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: tiktok
  labels:
    app: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      name: message-service
      labels:
        app: message-service
        version: "BUILD_HASH"
    spec:
      imagePullSecrets:
        - name: harborsecret
      containers:
        - name: message-service
          image: swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:latest
          imagePullPolicy: IfNotPresent
          command:
            - ./services/MessageService
          ports:
            - name: service-10008
              containerPort: 10008
              protocol: TCP
          volumeMounts:
            - name: project-etc-volume
              mountPath: /project/etc
            - name: project-logs-volume
              mountPath: /project/logs
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 128Mi
        - name: logger
          image: fluent/fluent-bit:1.8.4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: fluent-bit-conf
            - mountPath: /project/logs
              name: project-logs-volume
          command: [ "/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf" ]
      volumes:
        - name: project-etc-volume
          hostPath:
            path: /data/etc
            type: DirectoryOrCreate
        - name: project-logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
        - name: fluent-bit-conf
          configMap:
            name: fluent-bit-conf
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-api
  namespace: tiktok
  labels:
    app: message-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-api
  template:
    metadata:
      name: message-api
      labels:
        app: message-api
        version: "BUILD_HASH"
    spec:
      imagePullSecrets:
        - name: harborsecret
      containers:
        - name: message-api
          image: swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:latest
          imagePullPolicy: IfNotPresent
          command:
            - ./apis/MessageApi
          ports:
            - containerPort: 8896
              protocol: TCP
          volumeMounts:
            - name: project-etc-volume
              mountPath: /project/etc
            - name: project-logs-volume
              mountPath: /project/logs
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 128Mi
        - name: logger
          image: fluent/fluent-bit:1.8.4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: fluent-bit-conf
            - mountPath: /project/logs
              name: project-logs-volume
          command: [ "/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf" ]
      volumes:
        - name: project-etc-volume
          hostPath:
            path: /data/etc
            type: DirectoryOrCreate
        - name: project-logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
        - name: fluent-bit-conf
          configMap:
            name: fluent-bit-conf
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: message-api
  namespace: tiktok
spec:
  selector:
    app: message-api
  ports:
    - port: 8896
      targetPort: 8896
