---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relation-service
  namespace: tiktok
  labels:
    app: relation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relation-service
  template:
    metadata:
      name: relation-service
      labels:
        app: relation-service
        version: "BUILD_HASH"
    spec:
      imagePullSecrets:
        - name: harborsecret
      containers:
        - name: relation-service
          image: swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:latest
          imagePullPolicy: IfNotPresent
          command:
            - ./services/RelationService
          ports:
            - name: service-10006
              containerPort: 10006
              protocol: TCP
          volumeMounts:
            - name: project-etc-volume
              mountPath: /project/etc
            - name: project-logs-volume
              mountPath: /project/logs
          
        - name: logger
          image: fluent/fluent-bit:1.8.4
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: fluent-bit-conf
            - mountPath: /project/logs
              name: project-logs-volume
          command: [ "/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf" ]
      volumes:
        - name: project-etc-volume
          hostPath:
            path: /data/etc
            type: DirectoryOrCreate
        - name: project-logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
        - name: fluent-bit-conf
          configMap:
            name: fluent-bit-conf
      terminationGracePeriodSeconds: 30
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relation-api
  namespace: tiktok
  labels:
    app: relation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relation-api
  template:
    metadata:
      name: relation-api
      labels:
        app: relation-api
        version: "BUILD_HASH"

    spec:
      imagePullSecrets:
        - name: harborsecret
      containers:
        - name: relation-api
          image: swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:latest
          imagePullPolicy: IfNotPresent
          command:
            - ./apis/RelationApi
          ports:
            - containerPort: 8894
              protocol: TCP
          volumeMounts:
            - name: project-etc-volume
              mountPath: /project/etc
            - name: project-logs-volume
              mountPath: /project/logs
          
        - name: logger
          image: fluent/fluent-bit:1.8.4
          imagePullPolicy: IfNotPresent
          
          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: fluent-bit-conf
            - mountPath: /project/logs
              name: project-logs-volume
          command: [ "/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf" ]
      volumes:
        - name: project-etc-volume
          hostPath:
            path: /data/etc
            type: DirectoryOrCreate
        - name: project-logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
        - name: fluent-bit-conf
          configMap:
            name: fluent-bit-conf
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: relation-api
  namespace: tiktok
spec:
  selector:
    app: relation-api
  ports:
    - port: 8894
      targetPort: 8894
