---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: tiktok
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
        version: "BUILD_HASH"
    spec:
      containers:
        - name: user-service
          image: swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:latest
          imagePullPolicy: IfNotPresent
          command:
            - ./services/UserService
          ports:
            - name: service-10001
              containerPort: 10001
              protocol: TCP
          volumeMounts:
            - name: project-etc-volume
              mountPath: /project/etc
            - name: project-logs-volume
              mountPath: /project/logs
      volumes:
        - name: project-etc-volume
          hostPath:
            path: /data/etc
            type: DirectoryOrCreate
        - name: project-logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
      restartPolicy: Always
      imagePullSecrets:
        - name: harborsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  namespace: tiktok
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      name: user-api
      labels:
        app: user-api
        version: "BUILD_HASH"
    spec:
      containers:
        - name: user-api
          image: swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:latest
          imagePullPolicy: IfNotPresent
          command:
            - ./apis/UserApi
          ports:
            - containerPort: 8889
              protocol: TCP
          volumeMounts:
            - name: project-etc-volume
              mountPath: /project/etc
            - name: project-logs-volume
              mountPath: /project/logs

      volumes:
        - name: project-etc-volume
          hostPath:
            path: /data/etc
            type: DirectoryOrCreate
        - name: project-logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
      restartPolicy: Always
      imagePullSecrets:
        - name: harborsecret
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
  namespace: tiktok
spec:
  selector:
    app: user-api
  ports:
    - port: 8889
      targetPort: 8889