// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"min-tiktok/services/comment/comment"
	"min-tiktok/services/comment/internal/logic"
	"min-tiktok/services/comment/internal/svc"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) ActionComment(ctx context.Context, in *comment.ActionCommentRequest) (*comment.ActionCommentResponse, error) {
	l := logic.NewActionCommentLogic(ctx, s.svcCtx)
	return l.ActionComment(in)
}

func (s *CommentServer) ListComment(ctx context.Context, in *comment.ListCommentRequest) (*comment.ListCommentResponse, error) {
	l := logic.NewListCommentLogic(ctx, s.svcCtx)
	return l.ListComment(in)
}
