name: Code Review
on:
  pull_request:
    branches: [ testcr,main ]

permissions:
  pull-requests: write

inputs:
  chat-token:
    default: ${{ secrets.DEEPSEEK_CHAT_TOKEN }}
    required: true
    description: 'Your DeepSeek API token.'
  max-length:
    default: 0
    required: false
    description: 'The maximum length of the content for review, 0 means no limit.'
  model:
    required: false
    default: 'deepseek-chat'
    description: 'The DeepSeek model to choose for code review.'
  temperature:
    required: false
    default: 1.0
    description: 'The temperature of the model.'
  base-url:
    required: false
    default: 'https://api.deepseek.com'
    description: 'The base url of DeepSeek API.'
  sys-prompt:
    required: false
    default: "请专注于检查 Go 文件中的代码质量问题，包括但不限于代码风格、逻辑错误和安全漏洞，并提出具体的改进建议。"
    description: 'The system prompt for DeepSeek API.'
  user-prompt:
    required: false
    default: '请审查以下 Go 文件的代码变更'
    description: 'The user prompt for DeepSeek API.'
  include-patterns:
    required: false
    default: '**/internal/**/*'
    description: 'The comma separated file patterns to include in the code review.'
  exclude-patterns:
    required: false
    default: 'pnpm-lock.yaml,package-lock.json,*.lock'
    description: 'The comma separated file patterns to exclude in the code review.'
  github-token:
    required: false
    default: '${{ github.token }}'
    description: 'The GITHUB_TOKEN secret or personal access token to authenticate. Defaults to `github.token`.'
runs:
  using: 'composite'
  steps:
    - name: Setup Nu
      uses: hustcer/setup-nu@v3
      with:
        version: 0.102.0
    - name: DeepSeek Code Review
      shell: nu {0}
      run: |
        const NU_LIB_DIRS = [ ${{ github.action_path }}/nu ]
        use review.nu *
        let model = '${{ inputs.model }}'
        let baseUrl = '${{ inputs.base-url }}'
        let repo = '${{ github.repository }}'
        let token = '${{ inputs.chat-token }}'
        let ghToken = '${{ inputs.github-token }}'
        let sysPrompt = '${{ inputs.sys-prompt }}'
        let userPrompt = '${{ inputs.user-prompt }}'
        let pr = '${{ github.event.pull_request.number }}'
        let includePatterns = '${{ inputs.include-patterns }}'
        let excludePatterns = '${{ inputs.exclude-patterns }}'
        let maxLength = try { '${{ inputs.max-length }}' | into int } catch { 0 }
        let temperature = try { '${{ inputs.temperature }}' | into float } catch { 1.0 }
        (deepseek-review $token
          --model $model
          --repo $repo
          --pr-number $pr
          --gh-token $ghToken
          --base-url $baseUrl
          --max-length $maxLength
          --sys-prompt $sysPrompt
          --user-prompt $userPrompt
          --temperature $temperature
          --include $includePatterns
          --exclude $excludePatterns
        )
