name: Code Review
on:
  push:
    branches: [ dev,main ]
  pull_request:
    branches: [ dev,main ]

permissions:
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@v1
        with:
          chat-token: ${{ secrets.DEEPSEEK_CHAT_TOKEN }} # DeepSeek API Token
          model: deepseek-chat