name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login docker
      run: |
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin swr.cn-south-1.myhuaweicloud.com
    - name: build and push
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:$IMAGE_TAG .
        docker push swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:$IMAGE_TAG
