name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: build and push
        user: docker/build-push-action@v4
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          push: true
          tags: |
            swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:latest
            swr.cn-south-1.myhuaweicloud.com/lzb/min-tiktok:$IMAGE_TAG
